name: playaround
description: "PlayAround - Sports Social App for connecting athletes, booking venues, and tracking skills."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# App metadata for Play Store release
homepage: https://playaround.app
repository: https://github.com/playaround/playaround-app
issue_tracker: https://github.com/playaround/playaround-app/issues

# The following defines the version and build number for your application.
# Version format: MAJOR.MINOR.PATCH+BUILD_NUMBER
# For Play Store: version name = 1.0.0, version code = 1
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  cloudinary: ^1.1.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^3.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_offline: ^5.0.0
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  geoflutterfire_plus: ^0.0.32
  geolocator: ^14.0.2
  google_sign_in: ^7.1.1
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^8.0.1
  permission_handler: ^12.0.1
  rive: ^0.13.4
  shimmer: ^3.0.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  bloc_test: 10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animation/
    - assets/images/
    - assets/svgs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
