name: playaround
description: "PlayAround - Sports Social App for connecting athletes, booking venues, and tracking skills."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# App metadata for Play Store release
homepage: https://playaround.app
repository: https://github.com/playaround/playaround-app
issue_tracker: https://github.com/playaround/playaround-app/issues

# The following defines the version and build number for your application.
# Version format: MAJOR.MINOR.PATCH+BUILD_NUMBER
# For Play Store: version name = 1.0.0, version code = 1
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  csv: ^5.1.1
  cloudinary: ^1.1.0
  collection: ^1.18.0
  share_plus: ^12.0.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^3.0.0
  firebase_auth: ^5.3.1
  go_router: ^14.2.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_offline: ^5.0.0
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.2
  fake_cloud_firestore: ^3.1.0
  swipable_stack: ^2.0.0
  stripe_sdk: ^5.0.0
  gap: ^3.0.1
  geoflutterfire_plus: ^0.0.32
  geolocator: ^14.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^7.1.1
  http: ^1.1.0
  metadata_fetch: ^0.4.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.1.0
  intl: ^0.19.0
  location: ^8.0.1
  permission_handler: ^12.0.1
  uuid: ^4.4.0
  rive: ^0.13.4
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  table_calendar: ^3.1.2
  video_player: ^2.9.1
  video_compress: ^3.1.3
  video_thumbnail: ^0.5.3
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.5
  path_provider: ^2.1.3
  flutter_stripe: ^11.1.0
  timeago: ^3.7.0
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  zego_uikit_prebuilt_call: ^4.21.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  firebase_auth_mocks: ^0.14.1
  build_runner: ^2.4.9
  bloc_test: 10.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animation/
    - assets/images/
    - assets/svgs/
    - lib/core/i18n/
    # Demo placeholders excluded from production builds
    # Uncomment below only for development/testing
    # - mocks/
    # - assets/demo/placeholders/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#000000"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
